# Dependabot will run on day 3 of each month at 02:53 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    schedule:
      interval: "cron"
      day: 23
      timezone: "Europe/Berlin"
      cronjob: "53 2 3 * *"
    open-pull-requests-limit: 15
    assignees:
      - "tt-tom17"
    versioning-strategy: "increase"
    directories:
      - "**/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      day: 23
      timezone: "Europe/Berlin"
      cronjob: "53 2 3 * *"
    open-pull-requests-limit: 15
    assignees:
      - "tt-tom17"
